name: OakHouse Scraper

on:
  schedule:
    - cron: '0 12,18 * * *'  # 每小時運行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v4

      - name: 設置 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安裝依賴
        run: |
          pip install requests beautifulsoup4 python-telegram-bot
          pip install playwright
          playwright install  # 安裝 Playwright 所需的瀏覽器

      - name: Debug ENV
        run: echo "Token 是 $TELEGRAM_BOT_TOKEN, Chat ID 是 $TO_LIYING_CHAT_ID！"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TO_LIYING_CHAT_ID: ${{ secrets.TO_LIYING_CHAT_ID }}

      - name: 執行爬取腳本
        run: python scraper.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TO_LIYING_CHAT_ID: ${{ secrets.TO_LIYING_CHAT_ID }}